version: 0.2
phases:
  build:
    commands:
      - aws deploy push --application-name task5-CodeDeploy --s3-location s3://task5-s3-20250415/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src